### ISSUE TITLE
PlayerChangeHeldSlotEvent#getSlot() returns the old slot, not the new one.

### ISSUE THREAD

**Issue by Tofaa2** [Minestom/Minestom#1257]
As the title says, when calling event.getSlot() you get the old slot, not the new slot.

Code used in test:
```java
public class PlayerChangeHeldSlotListener implements EventListener<PlayerChangeHeldSlotEvent> {
    @Override
    public @NotNull Class<PlayerChangeHeldSlotEvent> eventType() {
        return PlayerChangeHeldSlotEvent.class;
    }

    @Override
    public @NotNull Result run(@NotNull PlayerChangeHeldSlotEvent event) {
        byte slot = event.getSlot();
        ItemStack item = event.getPlayer().getItemInMainHand();
        if (item.isAir()) {
            event.getPlayer().sendMessage("AADOSAJDOSAIJDASO");
            return Result.SUCCESS;
        }
        event.getPlayer().sendMessage("This will be ran even if you switch to air from an item that isnt air");
        return Result.SUCCESS;
    }
}
```

Shouldn't be a difficult fix

**Comment by GreatWyrm** [comment]
Just checked the code, and that is because the `getItemInMainHand()` function relies on the currently held slot, which is updated after all event listeners finish.
To get the item in the new slot, I believe `event.getPlayer().getInventory().getItemStack((int) slot));` would work, but that's not ideal. The PlayerChangeHeldSlotEvent could be modified to have a old slot and new slot variable, like Spigot equivalent event has.

**Comment by Tofaa2** [comment]
> Just checked the code, and that is because the `getItemInMainHand()` function relies on the currently held slot, which is updated after all event listeners finish. To get the item in the new slot, I believe `event.getPlayer().getInventory().getItemStack((int) slot));` would work, but that's not ideal. The PlayerChangeHeldSlotEvent could be modified to have a old slot and new slot variable, like Spigot equivalent event has.

Thanks for the explanation, I will mark the issue as solved now
