### ISSUE TITLE
Light is broken

### ISSUE THREAD

**Issue by TomJuri** [Minestom/Minestom#1289]
Long black stripes of darkness will appear around the world, they won't update when you place a block, unless it's a light source.
![image](https://user-images.githubusercontent.com/99533320/181765661-3971883c-5c02-4fbd-8aeb-502889a5a3d3.png)
Client: Forge 1.18.2 with only Optifine
OptifineSupport is enabled

**Comment by MrGazdag** [comment]
This is due to the fact that Minestom does not have a light engine at the moment. This is expected behavior. There is a light branch, its PR (#1109 ) is waiting to be merged at the moment. If you don't need lighting, you can set the dimension's ambient light level to `2f` to force a fully lit world.

**Comment by TomJuri** [comment]
Oh, alright thank you!
