### ISSUE TITLE
InventoryPreClickEvent is not called when a creative player is moving items inside their own inventory

### ISSUE THREAD

**Issue by bananasmoothii** [Minestom/Minestom#1343]
### Discussed in https://github.com/Minestom/Minestom/discussions/1317

<div type='discussions-op-text'>

<sup>Originally posted by **bananasmoothii** August  7, 2022</sup>
I've found that I have to use `InventoryPreClickEvent` to cancel an event in an `Inventory` (could you also explain me why `InventoryClickEvent` is not cancellable ?), but then I found that `PlayerInventory` does not extend `Inventory`, so using `InventoryPreClickEvent` doesn't work.</div>

**Comment by MrGazdag** [comment]
Creative players’ inventories work in a weird way, basically, whenever you click on an item in creative, the server thinks that item has disappeared. When you put the item back in your inventory, the server thinks you created a new item with some NBT data. This is because you can just create items out of thin air using the saved hotbars, or just the regular blocks/items in the creative menu. The server does not know about the cursor item of a creative player. This is not a minestom bug.

**Comment by bananasmoothii** [comment]
Oh, ok...
