### ISSUE TITLE
WitherSkull Entity is not invisible after setting it

### ISSUE THREAD

**Issue by einfachBlu** [Minestom/Minestom#1544]
![image](https://user-images.githubusercontent.com/54118058/204341462-61fbc904-7cd6-4998-9add-1f246c931c4a.png)

Code used for this example:
```java
for (String line : lines) {
      Entity nameTagEntity = new Entity(EntityType.WITHER_SKULL);
      if(nameTagEntity.getEntityMeta() instanceof WitherSkullMeta meta){
        meta.setCustomName(Component.text(line));
        meta.setCustomNameVisible(true);
        meta.setInvisible(true);
        meta.setHasNoGravity(true);
      }

      nameTagEntity.spawn();
    }
```

When i use EntityType.ARMOR_STAND and ArmorStandMeta instead, it is working. But not for Wither Skulls in Minestom.

**Comment by Steanky** [comment]
The invisible meta, despite being available for all entities, only seems to have an effect on armor stands (tested on 1.19.2). This is a vanilla "feature". You can spawn a skull using the command `/summon minecraft:wither_skull ~ ~ ~ {Invisible:1b}` and it will be visible. The same command, however, will make armor stands invisible, which is what you observed with your code as well.

If you want to make skulls invisible, you need to use an invisibility potion effect, which you can apply using the method `Entity#addEffect(Potion)`.

Note that you probably should add the entity to the instance *before* doing this, since unlike setting metadata, applying an effect will send a packet to update the client.
