### ISSUE TITLE
Automatically determine whether a tool should insta break a block.

### ISSUE THREAD

**Issue by devwckd** [Minestom/Minestom#2338]
Minestom has a weird little quirk that a variable has to be set to true for the player to be able to instantly break blocks using a powerful tool. This is annoying to set since it doesn't take the player's tool and attributes into account and may be abused by hackers. It being reset every gamemode change makes it worse. 
I implemented a basic version of Spigot's algorithm that determines if the block should be insta mined and I want to know if it fits here and I should open a PR or I should just keep it in a fork.
The code is available here https://github.com/devwckd/Minestom/commit/56cb446190ee5f66989371a1687ffc20f7285c7f and it's very simple.
Let me know if I should open a PR and if the code is good enough for the codebase :)

**Comment by ArjixWasTaken** [comment]
Minestom does not even have item drops by default, why should it have this feature?

Especially since a server may not want such behaviour

**Comment by GreatWyrm** [comment]
The commit looks mostly good to me, needs some nullability annotations and some other minor cleanup, but aside from that the code looks good.

I'd say Minestom should have this feature, since as far as I understand the issue it causes some pretty major desync between client and server, and that shouldn't be the case.

@ArjixWasTaken I'm not sure what server would be against that behavior when you have to explicitly make the ItemStack have block breaking components. If you've got an example of a server that would not want this default behavior, perhaps it should be made a ServerFlag (something like `ServerFlag.ALLOW_TOOL_INSTA_BREAK`).

**Comment by devwckd** [comment]
> Minestom does not even have item drops by default, why should it have this feature?
> 
> Especially since a server may not want such behaviour

The code has a `FIXME: verify mineable tag and enchantment` that implies that it was going to be looked at.
I can't think of a situation that a server wouldn't want an insta break tool to break blocks instantly to be honest.
Having an easy way to implement it with the API would be good but I don't think there is one and the `Player#setInstantBreak` solution is just hacky and annoying.

**Comment by LoboMetalurgico** [comment]
In my view this is extremely useful and could be implemented by default

**Comment by DasBabyPixel** [comment]
#2340 has a complete calculation for break speed and fixes the issue with insta mining

**Comment by GreatWyrm** [comment]
Done in 202889b8543905a30ddd9952e71461d3413b77a2.
