### ISSUE TITLE
Potential Memory Leak or Crash in ClientPluginMessagePacket

### ISSUE THREAD

**Issue by TheMeinerLP** [Minestom/Minestom#2439]
### Problem
The following test case generates `ByteArrays` with content through the call `reader.read(RAW_BYTES)`:

```java
@Test
void testClientPluginMessagePacket() {
    NetworkBuffer networkBuffer = new NetworkBuffer();
    ClientPluginMessagePacket clientPluginMessagePacket = new ClientPluginMessagePacket("channel", new byte[0]);

    clientPluginMessagePacket.write(networkBuffer);

    var packet = new ClientPluginMessagePacket(networkBuffer);

    assertEquals("channel", packet.channel());
    assertArrayEquals(new byte[0], packet.data());
}
```

### Expected Behavior
The test should generate an empty `ByteArray` and not contain any data.

### Actual Behavior
The test case generates `ByteArrays` with content through the call `reader.read(RAW_BYTES)`, although an empty `ByteArray` is expected.

### Steps to Reproduce
1. Create an instance of `NetworkBuffer`.
2. Create an instance of `ClientPluginMessagePacket` with an empty `ByteArray`.
3. Write the packet to the `networkBuffer`.
4. Read the packet from the `networkBuffer`.
5. Compare the channel and data array with the expected values.

### Potential Impact
This behavior can potentially cause the server to run out of memory (OOM) or crash.

**Comment by mworzala** [comment]
This is due to the way that the `RAW_BYTES` type works [in the protocol](https://wiki.vg/Protocol#Clientbound_Plugin_Message_.28play.29): the length is inferred from the size of the packet. 

When you create a network buffer it allocates a 1024 size byte buffer, and then you write the string to it. Then when you read back, we read the string and then arrive at the `RAW_BYTES` segment with ~1k bytes left in the buffer. It is correct behavior to read all of those bytes.

In normal operation, a limit will be set on the byte buffer to match the packet length so this does not occur. Here is an updated test case:
```java
    @Test
    void testClientPluginMessagePacket() {
        ByteBuffer buf = ByteBuffer.allocateDirect(1024); // The default from NetworkBuffer
        NetworkBuffer networkBuffer = new NetworkBuffer(buf);
        ClientPluginMessagePacket clientPluginMessagePacket = new ClientPluginMessagePacket("channel", new byte[0]);

        clientPluginMessagePacket.write(networkBuffer);
        buf.limit(networkBuffer.writeIndex());

        var packet = new ClientPluginMessagePacket(networkBuffer);

        assertEquals("channel", packet.channel());
        assertArrayEquals(new byte[0], packet.data());
    }
```

For some reason we incorrectly did not allow a 0-length buffer in this packet. I have fixed that in https://github.com/Minestom/Minestom/commit/0ca1dda2fe11390a1b89a228bbe7bf78fefc73e1
