### ISSUE TITLE
State Desync between Server and Client

### ISSUE THREAD

**Issue by GreatWyrm** [Minestom/Minestom#2457]
Attempting to send any packets to a logging-in player during the PlayerProvider will fail.

Example:
```
MinecraftServer.getConnectionManager().setPlayerProvider((connection, gameProfile) -> {
    connection.fetchCookie("some-value").thenAccept(...);
});
```
This sends a CookieRequest packet, which will disconnect the client.

This is due to the following sequence:
Minestom sends a LoginSuccessPacket to the client, the client switches to Configuration and responses with ClientLoginAcknowledgedPacket. This is handled by loginAckListener, which calls `MinecraftServer.getConnectionManager().createPlayer();` (using the player provider), and then switches the server's state of that Player to configuration. Before the end of that function, the server and client's states are desynced, with the server thinking the player is in the Login state and the client being in the Configuration state.
This can be resolved by manually setting the connection state to Configuration at the start of the function, but that may have unintended side effects.

**Comment by mworzala** [comment]
The exact state issue here was fixed in https://github.com/Minestom/Minestom/commit/be5ebb8060ee87b9b8d84238b6f3782175115d72, however fetching cookies is now explicitly prohibited as of https://github.com/Minestom/Minestom/commit/38e6c72ce41d257549941dde533d91886802975b. 

There is some explanation of why in the second commit above, if you were planning to do this you should instead fetch the cookies in the `AsyncPlayerPreLoginEvent` or `AsyncPlayerConfigurationEvent` depending on the use case.
