### ISSUE TITLE
1.21.2 type missmatch for Potions

### ISSUE THREAD

**Issue by BradBot1** [Minestom/Minestom#2474]
The class `Lnet/minestom/server/potion/CustomPotionEffect$Settings;` has the `#attribute;I` property despite `Lnet/minestom/server/potion/Potion;` having the `#amplifier;B` type making an explicit unsafe cast requried.

This can be easily fixed by changing `Lnet/minestom/server/potion/CustomPotionEffect$Settings#I` to `Lnet/minestom/server/potion/CustomPotionEffect$Settings#B`. (Aswell as related methods)

**Comment by GreatWyrm** [comment]
I'm somewhat confused by this issue.
CustomPotionEffect doesn't have an attribute property? I assume you mean amplifier, similar to Potion.
Explicit casting is needed to convert from an int to byte and vice versa, yes, but it's not unsafe? If there's something in Java that makes that cast unsafe, let me know.

Additionally, is the recommendation by the issue to switch everything to a byte? I'd assume so with the `#B`, but that's not really what should be done. The [network protocol](https://wiki.vg/Protocol#Entity_Effect) specifies it as a VarInt, and [NBT format](https://minecraft.wiki/w/Potion#Item_data) specifies it as a byte.

If anything changes I'd say it should be the Potion class that changes it to a int so the network type reflects a VarInt.

**Comment by BradBot1** [comment]
Hi, thanks for the reply. A few addendums:
1. Sorry about the typo I meant amplifier instead of attribute
2. It's CustomPotionEffect.Settings that has the amplifier property marked as an int, CustomPotionEffect just elevates access via a method
3. int to byte conversions are unsafe as the following is true: (int)((byte)128) == -128 As can be seen the int is now negative, despite origionally being positive (you can see code to test this yourself below). This can mean that a user's potion level could be interpreted as negative despite a positive value being present.
```java
int a = 128;
byte b = (byte) a;
int c = (int) b;
System.out.println(a + " " + b + " " + c); // prints 128 -128 -128
```
4. I didn't know the spec outlined them differently as the vanilla command limits users to 255 and the data component I am getting the instance from [Consumable limits it to a byte only?](https://minecraft.wiki/w/Data_component_format#potion_contents) Maybe the int is a left over that is still being migrated? Either way mojang clearly intend a max of 255 being sent/used

**Comment by GreatWyrm** [comment]
Alright, I understand now.
That said, I still wouldn't call a int -> byte cast unsafe. The number is pretty different, yes, but that's because a byte ranges from -128 to 127, so you can't store 128 into a byte. Would you consider a double to an int cast unsafe because it also changes the number (by truncating the fractional part)? 
Unsafe casting in my mind is more casting incompatible data types, like casting a struct in C to some other struct and reading the fields of the one you casted it to. Possible, but has a good chance of causing undefined behavior and behaving badly.

Aside from arguing over semantics, I think the best option is to change Potion to have an int amplifier and also validate bounds in the constructor of CustomPotionEffect.Settings and Potion.

**Comment by BradBot1** [comment]
Fair enough, when I use unsafe I moreso meant that a developer can easily introduce bugs and issues with it (IE an anti pattern) or make difficult to understand code. As for your solution that's fair, I just don't want to cast to use two adjacent objects.

**Comment by mworzala** [comment]
I ended up fixing this the opposite way. Potion is now an int which matches the protocol.
