### ISSUE TITLE
Some painting variants causes client disconnection

### ISSUE THREAD

**Issue by bluroch** [Minestom/Minestom#2479]
**Summary**
I tried to write a painting loader which could load paintings from Anvil worlds, but some variants make my client disconnect instantly, when I can join the variants are incorrect.

Here's a link to my code: [repository](https://github.com/bluroch/elderwood-experiments/tree/base-code)

**Details**
Variants are incorrect on the loaded paintings, also some variants are making clients disconnect.
![Paintings on Minestom](https://github.com/user-attachments/assets/be608515-17a5-485a-a29d-94c7bd2beb08)
![Paintings on Paper](https://github.com/user-attachments/assets/3155cdac-12fe-4ddc-9a08-b5a0923a7a98)
I included a debug world which has all painting variants with all orientations, see `worlds/gallery` in the linked repository. This is the world which makes the clients disconnect, the images are from a separate world that I want to load.

I suspect that I can join when that world is loaded only because I didn't used all variants there.

The repository also contains one of my disconnect logs: `logs/client/painting_error.txt`

**Comment by mesoscopic** [comment]
It's such a relief to see someone else struggling with paintings :)

My first instinct was a mismatch between the registry on the server and that on the client, which is corroborated by your error log, so I dug into the codebase.
As specified in the [protocol](https://wiki.vg/Protocol#Serverbound_Known_Packs), Minestom only sends registry data for a datapack (in this case, the `minecraft:painting_variant` registry in the vanilla data pack) if the client reports not already having it. Since the vanilla client always has the vanilla data pack, the painting_variant registry isn't sent.
Something on Minestom's end is generating the registry different from how it is on the client, hence the mismatch.

Why is that? Well, the answer is really simple. The entries in the registry [aren't](https://github.com/Minestom/Minestom/blob/master/src/main/java/net/minestom/server/registry/DynamicRegistry.java#L86) sorted alphabetically [like they are in the vanilla client](https://github.com/misode/mcmeta/blob/registries/painting_variant/data.json).

As far as I can tell, passing a comparator [here](https://github.com/Minestom/Minestom/blob/master/src/main/java/net/minestom/server/entity/metadata/other/PaintingMeta.java#L107) should fix this issue.

**Comment by mesoscopic** [comment]
Actually, the error you're getting would imply a mismatch in size between the client and server packs, but there aren't any paintings missing from the data and I couldn't find anything else that might cause an overflow. I'll do some actual testing soon.
