### ISSUE TITLE
Chunks disappear when reconnecting / breaking blocks.

### ISSUE THREAD

**Issue by LeoDog896** [Minestom/Minestom#290]
When an (unknown) amount of blocks break, usually a layer of a chunk, that chunk and chunks around it stop rendering and colliding properly with the client.

**Comment by Uraxys** [comment]
After testing it myself it looks like it only happens after you break 200 blocks, any more and the chunk (16x16x16) will be removed, if I place a block after the chunk disappeared then it shows up again, but if I remove another block / the one I placed then it gets removed.

Also, it looks like it only happens if you break 200 blocks that was there when it was rendered, if you place 200 blocks and break it again then the chunk won't be removed.

**Comment by TheMode** [comment]
> After testing it myself it looks like it only happens after you break 200 blocks, any more and the chunk (16x16x16) will be removed, if I place a block after the chunk disappeared then it shows up again, but if I remove another block / the one I placed then it gets removed.
> 
> Also, it looks like it only happens if you break 200 blocks that was there when it was rendered, if you place 200 blocks and break it again then the chunk won't be removed.

I assume that the client believes that he has a wrong version of the chunk, but we haven't been able to find why

**Comment by TheMode** [comment]
Fixed by #299
