### ISSUE TITLE
Investigate Prometheus

### ISSUE THREAD

**Issue by mworzala** [Minestom/Minestom#310]
Prometheus is a popular monitoring framework, which could be integrated into Minestom to provide metrics and alerting. 

Need to look into the feasibility and usefulness.

[Docs](https://prometheus.io/docs/introduction/overview/)
[Java Library](https://github.com/prometheus/client_java)

**Comment by ZakShearman** [comment]
Personal opinion: Should be added purely as an extension that people can have, not integrated directly into the server.

**Comment by mworzala** [comment]
> Personal opinion: Should be added purely as an extension that people can have, not integrated directly into the server.

Having it as an extension would be a nightmare (would need to be done pretty much exclusively with mixins), though it certainly would never be a requirement that you make use of it even if its added.

**Comment by ZakShearman** [comment]
hmm if it would be a nightmare like that then yh. Avoid it.

What would cause the use of mixins to be necessary?

**Comment by mworzala** [comment]
The placement of metric gathering, you would need to inject it into a bunch of methods most likely, though I haven't looked deep into it.

**Comment by Bloeckchengrafik** [comment]
Have you considered building a metrics api?
That may provide the opportunity for people to integrate other metric collection apis with Minestom.

for example, i built a private metric collection api that does not work with prometheus. Also one could integrate stuff like NewRelic, Netdata or for the crazy people even splunk

**Comment by ZakShearman** [comment]
Nowerdays you wouldn't build it for Prometheus or NewRelic - you'd just implement OpenTelemetry which supports tons of them and it becoming a standard now.

I never ended up doing a public kind of API, for EmortalMC we just have it directly integrated for prometheus as that's what we use and it's simple.

If someone wanted to do it, they should look into OpenTelemetry and see how others add metrics to that n stuff. Also likely more suitable as an extension/library rather than built-into Minestom tbh.
