### ISSUE TITLE
Server UI

### ISSUE THREAD

**Issue by TheMode** [Minestom/Minestom#398]
Offer an official UI for monitoring and debugging purpose. Perhaps as an extension, or directly integrated in the repo depending on the dependency graph.

Possible features:
* Console
* Memory graph
* Process usage, mspt, per thread usage
* Entity tab, possibility to query entities using the [target selector](https://minecraft.fandom.com/wiki/Target_selectors) syntax. Clicking on one should show the "entity editor" page where every part of the entity can be modified
* Tag editor, ability to view in real time the tags applied to an entity, block, instance & chunk.
* Packet listening (debugging purpose)
* Provide an API for other extensions to create their own tab
* Include [async-profiler](https://github.com/jvm-profiling-tools/async-profiler)
* Entity pathfinding debugger (show target, path, goal, etc) (maybe part of an entity viewer/editor)
* Event graph viewer (to see them triggering in realtime perhaps)
* Some kind of block handler info? (time stats? count?)
* File browser/basic text editor (restricted to server working directory)
* "Item editor" (or part of entity editor)

**Comment by Eoghanmc22** [comment]
i think this should be done with some kind of "official extension." but if this is offered as a official extension with access to sensitive information like console and files then great care need to be taken to make it secure.

**Comment by Eoghanmc22** [comment]
also idk the best way to implement this but it would be cool if it worked with multiple servers and supported adding servers dynamically.

possible model
web client <-> web panel <-> minestom servers with extension

**Comment by ZakShearman** [comment]
I've started working on what will aim to be this just as a bit of fun to see if I can get anywhere, but it's likely I'll stall after a bit.

I have no idea how I'm going to make the UI element because I want it to work with both a single server that will run the panel, and also as part of a cluster where the server can register itself with a master node.

If anyone has any suggestions regarding anything feel free to ping me on discord (Zak).
