### ISSUE TITLE
Unable to import ChunkGenerator class

### ISSUE THREAD

**Issue by SJS830** [Minestom/Minestom#54]
Hi, I am unable to import the chunk generator class. Here is the error:

`Error: Unable to initialize main class myclass
Caused by: java.lang.NoClassDefFoundError: net/minestom/server/instance/ChunkGenerator`

My code is copied from the complete example from https://github.com/Minestom/Minestom/wiki/Server-setup. I am getting the dependency from jitpack and compiling using maven. Is this a known issue?

**Comment by TheMode** [comment]
This is probably because the ChunkGenerator class has been switched into an interface
You can replace "extends ChunkGenerator" by "implements ChunkGenerator", normally your IDE always warned you. Did update the wiki to reflect the change

**Comment by SJS830** [comment]
I changed it to `implements` but I get the same error.

**Comment by SJS830** [comment]
I tried building the same code using gradle and the same error occurs. Just to be sure, what tag number should I use for compilation? Right now I'm using "master."

**Comment by TheMode** [comment]
Here is the one we use for the vanilla implementation
https://github.com/Minestom/VanillaReimplementation/blob/master/build.gradle
The last commit id we have is "daaa126"

Honestly, I don't know about maven so I'm unable to help you with it. As for Gradle if you are even unable to run Minestom or the vanilla implementation by forking then the issue lies probably somewhere else

**Comment by SJS830** [comment]
You're right, the problem was that maven wasn't packaging the dependencies in my jar. Sorry for wasting your time.
