### ISSUE TITLE
Item frame / glowing item frame entities reset orientation after ~1 minute

### ISSUE THREAD

**Issue by emortaldev** [Minestom/Minestom#760]

**Comment by iam4722202468** [comment]
It seems like maps change their orientation based on `Entity Position and Rotation` and `Entity Rotation` packets. These packets are sent to the client to sync positions of entities every few minutes.

What I think is happening is by default, the entity position has yaw/pitch set to 0. When this update is sent to the client, it causes the map orientation to reset. 

This can be fixed by setting the entity yaw value to whatever direction the frame is supposed to be facing.

**Comment by KrystilizeNevaDies** [comment]
> It seems like maps change their orientation based on `Entity Position and Rotation` and `Entity Rotation` packets. These packets are sent to the client to sync positions of entities every few minutes.
> 
> What I think is happening is by default, the entity position has yaw/pitch set to 0. When this update is sent to the client, it causes the map orientation to reset.
> 
> This can be fixed by setting the entity yaw value to whatever direction the frame is supposed to be facing.

This is exactly right, this is a client bug and you need to set both the meta and the itemframe's rotation to the correct values.

**Comment by Distractic** [comment]
For interested people, this is the yaw and pitch to define according to the orientation :

```kt
val yaw = when(orientation) {
       ItemFrameMeta.Orientation.SOUTH -> 0f
       ItemFrameMeta.Orientation.WEST -> 90f
       ItemFrameMeta.Orientation.NORTH -> 180f
       ItemFrameMeta.Orientation.EAST -> 270f
       else -> 0f
}

val pitch = when(orientation) {
       ItemFrameMeta.Orientation.UP -> 270f
       ItemFrameMeta.Orientation.DOWN -> 90f
       else -> 0f
}
```
